# FROM openjdk:18-ea-11-jdk-alpine
# ARG JAR_FILE=build/libs/*.jar
# COPY ${JAR_FILE} app.jar

FROM adoptopenjdk/openjdk11
CMD ["./mvnw", "clean", "package"]
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=prod", "-jar", "app.jar"]
